name: Release - demo-aiko-personalisation-we

on:
  release:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: read

env:
  VERSION_TAG: ${{ github.event.release.tag_name }}  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prodxansrcoreacrci.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f629ab18ca30437b8d4ad19661f67b5b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aba30d90c450451690661d53d9573a22 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: prodxansrcoreacrci.azurecr.io/aikopersonalisationms:${{ env.VERSION_TAG }}
        file: ./Dockerfile

 